export { default as WhiteboardDialog } from './components/WhiteboardDialog.vue'
export { default as WhiteboardPanel } from './components/WhiteboardPanel.vue'
export { useWhiteboardDialog } from './composables/use-whiteboard-dialog'
export { setupStageUiWhiteboard } from './register'
export { useWhiteboardCanvasStore } from './stores/whiteboard-canvas'
export { useWhiteboardDialogStore } from './stores/whiteboard-dialog'
export { createWhiteboardTools } from './tools/create-whiteboard-tools'
export type { Canvas, CanvasPath } from './types/canvas'
